### ISSUE TITLE
[Max] transparency checkbox in material not respected

### ISSUE THREAD

**Issue by PatrickRyanMS** [BabylonJS/Exporters#300] opened 2018-08-21 22:46 UTC
Unchecking Transparency in the material options does not export material with an OPAQUE blendmode. Materials exported no matter if there is a transparency map linked to the material input or if the transparency checkbox is checked or unchecked will write out as blendmode = "BLEND"

**Comment by sebavan** [comment] 2018-08-21 22:54
Adding @noalak and @Jaskar for follow up, Thx guyz.

**Comment by noalak** [comment] 2018-08-22 07:18
Hi Patrick!

Do you have a repro scene ? Couldn't reproduce with simple tests.

Except a bug, the only reason for a material to be in BLEND is that it contains alpha somehow:
- has an opacity / transparency weight map or opacity / transparency value
- has a diffuse color / base color map with 'Alpha Source' set to 'Image Alpha'

(first attribute is the Standard material one **/** the second is the Physical material one)

**Comment by deltakosh** [comment] 2018-08-23 16:01
Pinging @PatrickRyanMS

**Comment by PatrickRyanMS** [comment] 2018-08-23 19:10
Sent you the Max file. Let me know if you have questions.

**Comment by noalak** [comment] 2018-08-27 10:04
Hi Patrick,

I have received the files. The 2019 version shouldn't be the issue as it is also happening on 2018.

The base color map of the lens material has an Alpha Source set to 'Image Alpha'.
In this case,

- if you provide a Transparency **Weight** map, the alpha channel of the base color map is ignored and the transparency map is used instead.
- otherwise, the alpha channel of the base color is directly used. The base color and alpha (opacity) maps are assumed to be already merged.

For you, it is the 2nd case. If you want the material to be in OPAQUE mode, turn the Alpha Source to None.

Things to consider here:

- The 3ds max exporter is looking at the Transparency **Weight**, not the Transparency Color. In Maya you don't have such distinction.
- 3ds max Physical material is using Transparency while Maya Stingray PBS and AiStandardSurface materials are using Opacity. This means that you can't directly use an opacity map from Maya. You need to manually invert it to transparency.

The Maya to 3ds Max worflow has never been examined. We could improve it for sure!
To understand the worflow and how you get the files you sent me:
- did you use an automatic conversion process (like Maya 'Send to 3ds Max' feature) ?
- regarding materials were the results as expected ?
- did you manually reset/edit the materials ?

The transparency vs opacity issue could be adressed by adding a Babylon Attribute to the material, like an InvertAlpha checkbox. See issue #292 for what it would look like. The exporter would then invert the map for you. However note that this process could take a long time and would be performed each time.
For this issue, what you are looking for is probably a Maya to 3ds Max assistant plugin.

For the transparency weight vs color, we could use the Alpha channel of the transparency color if no transparency weight is set.

Let me know you think about it.

**Comment by noalak** [comment] 2018-09-05 07:26
@PatrickRyanMS bump

**Comment by PatrickRyanMS** [comment] 2018-09-06 18:45
@noalak I apologize for the delay in swinging back to this. The connection from the base color into transparency color was my mistake. I simply connected to the wrong input on that one, but even correcting the wire does not solve what I am seeing. 

Here's my path to Max:
* The asset was created in Maya, but rather than use Send To Max, I used the FBX to recreate the asset in Max
* Import the FBX
* Create and wire the materials manually
* Uncheck all transparency boxes for materials that need to be in the OPAQUE queue
* Assign Opimize mesh in Babylon Options
* Export with Tangents to glTF
* Check glTF code for blend modes on materials and manually edit values if they are wrong.

Below you can see two of the materials in the Slate editor. The selected material shows the transparency boxes unchecked and no map connection to the transparency inputs. The other material is the one that needs to be in the TRANSPARENT queue and has a map wired to the transparency input. 

Below that image is a screen shot of the glTF output of the material with all transparency options disabled. All of my materials end up with alphaMode: BLEND instead of OPAQUE (or nothing) for the other materials and BLEND on the one that has transparency wired. 

I understand what you are saying when talking about transparency vs opacity in Max/Maya, but before we even get to that, I'd like to understand how to set up the materials so that I don't need to manually edit the glTF file to get it to display as expected. 

![slateeditor](https://user-images.githubusercontent.com/31326855/45177684-7dfb5900-b1c8-11e8-8a1d-85bd7a5b9c72.PNG)

![maxblendmode](https://user-images.githubusercontent.com/31326855/45178165-d97a1680-b1c9-11e8-8c89-cc4c7504712c.PNG)

**Comment by noalak** [comment] 2018-09-07 11:58
So i reproduced the bug you have @PatrickRyanMS . In the sample file provided (FlightHelmet_Optimized_2018.max), all materials are exported with alphaMode=BLEND in gltf.

The issue is that the Alpha Source attributes of the textures are not initialized correctly in 3ds max.
When assigning a texture to a material, the internal value of Alpha Source of the texture is the default one (0), corresponding to 'Image Alpha'. Once entered texture settings, 3ds max initializes the Alpha Source value. For a jpg or png without alpha, the 'Image Alpha' is darken and the Alpha Source is set to 'None (Opaque)'. For a png with alpha, the Alpha Source remains to 'Image Alpha'.

@PatrickRyanMS Currently, the only way to export your scene correctly is to open the texture settings of all Base color textures used in your scene. Either double click on the texture in the Slate Material Editor or Double click on the texture in the Compact Material Editor. You don't need to modify anything, just displaying settings is enough. You will notice that the model in the viewport will be updated everytime you enter a texture settings.

My team and I never encountered such issue since we are using the Compact material editor and never perform drag&drops but instead enter the texture settings (empty) and then assign a texture from there with the Map Browser.

The 'solution' given to Patrick is clearly not a perfect one. I see 2 ways to fix it:
- From the exporter, remove the feature taking into account the alpha channel inside base color / diffuse color. If you want alpha, set the texture in the opacity map of the material. This is basically, ignore Alpha Source property (considered always None).
- Contact 3ds max developpers to fix that. Users with latest version will be able to assign textures without any trouble. Others (hum) won't.

I don't see other texture attributes which could have similar issue, but not 100% sure either...

**Comment by deltakosh** [comment] 2018-09-07 13:47
As this is a bug in autodesk 3dsmax I'm not sure we should do anything about it. If we ignore the alpha source then it will become impossible to have alpha testing

**Comment by noalak** [comment] 2018-09-07 14:00
Alright, do we write a note about this issue in the 3ds max doc ?

**Comment by deltakosh** [comment] 2018-09-07 14:45
yes definitely in bold ;)

**Closed** 2018-10-10 13:56 UTC
Labels: 3dsmax, bug
