### ISSUE TITLE
[3ds max] material warning: invalid rank

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#1070] opened 2022-07-17 16:52 UTC
Hi!

I am using exporter v20220617.2 with max 2023 and am encountering a strange issue while exporting. There is a warning regarding the material during export and this is most likely related to the incorrect display of the model, see:

![image](https://user-images.githubusercontent.com/15689124/179416097-c86197c6-6d94-4d20-91a6-29eea750fafc.png)
![image](https://user-images.githubusercontent.com/15689124/179416112-ab345b55-c112-471b-bfcc-e4fce222322c.png)

The sample file can be found here:
[acft_mdl.zip](https://github.com/BabylonJS/Exporters/files/9128149/acft_mdl.zip)

Thank you very much for your inputs!

**Comment by pandaGaume** [comment] 2022-07-18 10:26
Hello, the invalid rank message has nothing to do with the export process, it's mean we pass a wrong information into the message farmework at UI destination. It's might be an indication of error but we better focus on what's going wrong onto the export result (i guess materials on the wings) ? You better to use the [forum ](https://forum.babylonjs.com/)to ask question, as it's not a bug , yet ..

**Comment by tkazik** [comment] 2022-07-23 15:44
Thx for the pointer and sorry for opening the issue here directly.
The question on the forum can be found [here](https://forum.babylonjs.com/t/3ds-max-exporter-material-issues-on-glb/32426).
Do you mind keeping the issue open until we have clarity? Or would you prefer to close it in the meantime? Thx!

**Comment by thomlucc** [comment] 2022-10-03 18:21
Closing for now, based on forum feedback. Let us know if we need to re-open

**Closed by thomlucc** 2022-10-03 18:21 UTC
