### ISSUE TITLE
Animation with different behavior babylon vs glb

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Exporters#853] opened 2020-06-30 22:39 UTC
Please refer to the discussion on the forum: 

https://forum.babylonjs.com/t/animation-with-different-behavior-babylon-vs-glb/11948/24

TL/DR: https://playground.babylonjs.com/#BCU1XR#1387 5 look at legs from this position.

Difference in export step: 
ch1 - **exported only the geometry, I ment I selected only the object in 3ds Max and on export I checked ‘export only selected’, and this work good**
ch2 - **this was exported with default values of exporter, I choosed only the extension .glb**

Source model:
https://github.com/Bulisor/SmarTeam3D/tree/master/assets/test

**Comment by Drigax** [comment] 2020-07-01 15:25
Possible dupe of https://github.com/BabylonJS/Exporters/issues/851?

**Comment by Drigax** [comment] 2020-07-02 18:13
closing as duplicate.

**Closed by Drigax** 2020-07-02 18:13 UTC
Labels: 3dsmax, bug
