### ISSUE TITLE
Max2Babylon: white transparency texture shows albedo?

### ISSUE THREAD

**Issue by echadwick-wayfair** [BabylonJS/Exporters#714] opened 2019-12-12 15:49 UTC
The middle of the transparent circle is 255-white, so I think it should not show the RGB of the albedo. But it does?

Is there something incorrect in the material code here?

![2019-12-12 10_34_53-Babylon js - transp_two-pngs_v20191209-5 glb](https://user-images.githubusercontent.com/40177036/70725942-492f5900-1ccb-11ea-871d-ea7f2da39fee.jpg)

The 24bit PNG transparency texture is a circle with 255-white in the middle half, plus a radial gradient that transitions to black on the edges.
![radial](https://user-images.githubusercontent.com/40177036/70726177-a75c3c00-1ccb-11ea-8306-0a31441a9848.png)

The 24bit PNG albedo texture is a smoke pattern.
![smoke](https://user-images.githubusercontent.com/40177036/70726929-d58e4b80-1ccc-11ea-929f-8bd8ebf3c1cc.png)

So the center should be completely clear (except for showing specular reflections). However when bright parts of the IBL are reflecting across it, we see parts of the albedo RGB (the smoke pattern)

Physical Material setup uses two PNGs with no alpha, the smoke pattern in Base Color and the radial gradient in Transparency Weight, plus the attribute Transparency Mode: Blend

Example: (Max 2020 file, pngs, glb)
[transp_3dsmax2020_two-pngs_v20191209-5.zip](https://github.com/BabylonJS/Exporters/files/3956592/transp_3dsmax2020_two-pngs_v20191209-5.zip)

Max2Babylon 20191209.5
3ds Max 2020.2
Windows 10

Thank you!

**Comment by Drigax** [comment] 2019-12-13 01:27
I see what you mean, that's not right at all. Looks like the specular is being drawn over the transparent portions of the mesh. I don't think this is caused by the glTF itself, however.

In the babylon.JS loader, you can set `GLTFLoader.transparencyAsCoverage = true` to multiply the specular by the opacity:

![image](https://user-images.githubusercontent.com/3952729/70762208-a7c4f900-1d04-11ea-8c81-2da5c202bbe0.png)

hopefully this helps!

**Comment by echadwick-wayfair** [comment] 2019-12-13 14:54
I don't have a problem with specular being shown on fully-transparent surfaces. In fact, that needs to be preserved. Otherwise glass would be invisible.

The problem I noticed is the RGB of the albedo showing up in the specular. I would expect no albedo there, only specular.

**Comment by echadwick-wayfair** [comment] 2019-12-13 15:05
It seems to me the transparency texture should be masking the albedo texture. Where transparency is 255 white, the albedo should disappear completely. The albedo should not be contributing to the specular. When metalness is zero, the specular reflection should never be perturbed by albedo.

**Comment by Drigax** [comment] 2019-12-13 18:51
Should it though? I'm not entirely sure if this is on the renderer for not masking the albedo contribution to the specular color, or the artist (or exporter) for not masking out the translucent parts in the base color map. @sebavan, and @PatrickRyanMS what do you suggest?

**Comment by sebavan** [comment] 2019-12-16 18:43
I leave this one to @PatrickRyanMS cause it sounds closer to the artist workflow than the rendering side here :-)

**Comment by sebavan** [comment] 2019-12-16 18:44
Might be a special setup @PatrickRyanMS  ?

**Comment by echadwick-wayfair** [comment] 2020-01-06 21:10
If a model uses a checkerboard albedo, and the transparency is 100%, should any of the albedo appear? If I understand the rendering logic, the model should be completely clear except the brightest parts of the IBL (and the specular from analytical lights) should appear as reflections on the model. Full transparency should completely omit the albedo checkerboard.

**Comment by echadwick-wayfair** [comment] 2020-01-06 21:12
If metalness is 1.0, then the albedo is used as the reflection color. The checkerboard would appear in specular reflections, which would be (in effect) multiplied by the albedo checkerboard.

If metalness is zero, then the albedo should not affect reflection color, right?

**Comment by sebavan** [comment] 2020-01-06 21:28
@PatrickRyanMS  will be back tomorrow from vacation and will be glad to help.

Both specular and environment reflections if bright enough will appear (controlled by specularOverAlpha and useRadianceOverAlpha in the materials respectively) and reduce the transparency to mainly simulate effects like a TV reflecting on a window by night.

If metalness is 0 we will still see reflections. Think about a glossy ball for instance, even none metallic (actually think about polished plastic) you would still see some reflection and obviously more around the fresnel.

I bet @PatrickRyanMS will have way more detailed than my poor explanations (consider it a bad teaser)

**Comment by Drigax** [comment] 2020-01-23 17:47
@PatrickRyanMS is a bit busy with asset creation as we get closer to our next release. Hopefully he can find some time to provide his perspective as well.

This is definitely an important question, but I'm not sure if this is still related to the exporters specifically. Should we move this conversation to the babylon forums?

**Comment by Drigax** [comment] 2020-02-18 22:15
I'm going to close this issue for now, I'm not sure if this is particularly related to the exporter or renderer. We can always reopen or transfer this if needed.

**Closed by Drigax** 2020-02-18 22:15 UTC
Labels: 3dsmax, question
