### ISSUE TITLE
How to export Vray materials

### ISSUE THREAD

**Issue by tiantianaixuexi** [BabylonJS/Exporters#1099] opened 2023-08-18 09:06 UTC
Hello, I export ordinary materials in 3dmax2018, and then load them in Blender or UE4 with materials. But when I switch to the Vary material in 3DMAX, there is no material when exporting to Blender or UE. How can I export the Vary material?

![image](https://github.com/BabylonJS/Exporters/assets/31758095/82b8c93e-224c-439e-9a57-f927bc266270)
![image](https://github.com/BabylonJS/Exporters/assets/31758095/bcfdd777-9786-4b4b-99f0-f22a5abfcc4a)

**Comment by PatrickRyanMS** [comment] 2023-09-05 18:24
@tiantianaixuexi, I am guessing that you are exporting your assets from 3ds Max using the Babylon exporter to glTF. If that is not what you are doing, please let me know that I have made an incorrect guess. If that is what you are doing, we don't have support for VRay materials in our exporter. We needed to stick with materials available to the most users and so we support Physical Materials, Arnold Materials, PBR Materials - both metallic-rough and spec-gloss - and glTF materials that are all native to 3ds Max. We don't have plans to support other materials in Max at this moment. 

If you have other questions, we would love to answer them on our forum at https://forum.babylonjs.com/ where you have access to the entire development team and our wonderful community of users who will answer you quickly. I will close this issue as it's not a bug or feature request, but please do join us on the forum for more guidance, sharing ideas or knowledge, and discussions about the engine or features.

**Closed by PatrickRyanMS** 2023-09-05 18:24 UTC
