### ISSUE TITLE
[3ds max] Exporter Dlls don't let max exit cleanly

### ISSUE THREAD

**Issue by johanos** [BabylonJS/Exporters#180] opened 2018-05-10 16:26 UTC
Hey guys, I uncovered an issue with the way that the dlls are interacting with max.

when i have the babylon exporter dlls in the assemblies folder of max 2018 everything works fine but once i close max, i get a message that says

"3ds Max has stopped working" 

if i select the option to debug the program. it shows the following error

```Unhandled exception at 0x00007FFF32F98363 (ntdll.dll) in 3dsmax.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFF32FF06B0).```

if i remove the dlls from the babylon exporter from the bin folder, max will exit cleanly. 

this doesn't let me script max because it will hang right after it finishes and won't let it go to the next step in my process.

**Comment by johanos** [comment] 2018-05-10 16:32
More info: 

Windows 10 Build: 14393.2125 & Windows Server 2012 R2

Max Version: 2016 & 2018 

Exporter Version: 1.0.5

**Comment by noalak** [comment] 2018-05-22 12:47
Hi johanos,

Can't reproduce the bug. I'm using Windows 10 16299.431

**Comment by mattWayfair** [comment] 2018-06-20 20:33
I am seeing this bug as well.  It didn't start at first try for me but it is happening to me.

**Comment by deltakosh** [comment] 2018-06-20 20:34
Are you doing something specific or just opening max and then closing it is enough?
Can you provide a repro path?

**Comment by mattWayfair** [comment] 2018-06-20 20:35
I am using the exporter to create gtLF.

**Comment by deltakosh** [comment] 2018-06-20 20:36
I mean: does it happen even with a single box?

**Comment by mattWayfair** [comment] 2018-06-20 20:43
It happens now if I just open and close Max.  It didn't use to do it but once it started it always happens after that.  I don't have a better repo case but I will see if I can get one.

**Comment by deltakosh** [comment] 2018-06-20 20:44
This seems enough :)
which OS and max version?

**Comment by deltakosh** [comment] 2018-06-20 20:44
Pinging @noalak  for awareness

**Comment by johanos** [comment] 2018-06-21 13:47
If we remove the max2babylon.dll it stops crashing on close as well, we export glbs with the export selected, copy textures to path options in our maxscript. This showed up before the exporter got exposed to maxscript as well

**Comment by mattWayfair** [comment] 2018-06-21 13:52
Here is the dump file from the Max process that is hanging after I closed Max. 

[3dsmax.exe.10988.zip](https://github.com/BabylonJS/Exporters/files/2123844/3dsmax.exe.10988.zip)

**Comment by mattWayfair** [comment] 2018-06-21 13:53
On a VM running windows Server 2012 R2 I open a fresh install of Max and just closed it when it loaded up and got the error.  I have only been using Max 2018.

**Comment by mattWayfair** [comment] 2018-06-21 14:05
The OS I am using is MS Windows 10 Enterprise. Version 10.0.14393 Build 14393.
Max is 2018.

**Comment by noalak** [comment] 2018-06-21 15:16
I'm using the same 3ds max version 20.0.0.966.
You are both using Windows 10.0.14393, it might be the source of the issue. Could you try to update your windows? Current build version is 17134. It will update the ntdll.dll

**Comment by mattWayfair** [comment] 2018-06-21 19:47
I also isntalled the simplygon max plug in as well.  Maybe they are conflicting?

**Comment by mattWayfair** [comment] 2018-06-26 13:18
Its also happening on a machine running Windows Server 2012 R2 Version 6.3 build 9600

**Comment by mattWayfair** [comment] 2018-06-26 13:34
We cannot upgrade windows at this time due our security audits, could you do downgrade to our version of windows and see if you get the issue?

**Comment by noalak** [comment] 2018-06-27 14:57
Windows version can't be downgraded anymore.
We are trying to repro on a virtual machine as well.
Have you tried to update the exporter dlls ?

**Comment by johanos** [comment] 2018-06-27 15:56
Yeah we’ve maintained up to date with the dll releases you guys put out.

**Comment by Jaskar** [comment] 2018-07-02 07:35
There are some news.
3DsMax can't run on a virtual machine, so we're currently installing the specific version of Windows and Max on another PC.

**Comment by Bloadrick** [comment] 2018-07-03 14:47
Hey ,

I have tested on a real computer with the following specs : 

-Windows 10 pro build 14393
-3DS MAX version 20.0.0.966
-And Simplygone installed

And I still don't get your error, have you tested it on different computers or just one ?
Can it come from your enterprise system ? like an authorization in your active directory ?

**Comment by mattWayfair** [comment] 2018-07-03 15:38
We are getting the error on different computers.

**Comment by johanos** [comment] 2018-07-03 15:48
Our process also follows the following path
Max 2018 opens -> Simplygon Max Plugin called -> Render to Texture Dialog opened and used up to 5 times -> Simplygon Max Plugin Called -> (Export FBX via Max -> Export glTF via Plugin) x 2 -> max closed with `quitMax #noPrompt`

We're not sure what could be causing the ntdll to say "a heap was corrupted". maybe its our order of operations? we can try sharing the permissions on our directories.

**Comment by Bloadrick** [comment] 2018-07-03 16:09
Yes, I think it can be your process.

Can you share your script or explain how you are doing this procedure to see if we can reproduce it ?

**Comment by johanos** [comment] 2018-07-09 17:16
sorry for the delay
1) From command line call 3dsmax -q -silent -mxs "filein maxscript.ms"
2) max script does some processing on the mesh
3) Call the 3ds max simplygon plug in to decimate the model
5) mergeMAXFile @"our/network/path"
4) flattens all objects into one mesh, uv unwraps and packs the uvs using the unwrap_uvw modifier
5) use the render to texture dialog to create a texture atlas for the entire model. 
6) do this for a couple other bake elements with different settings
7)  call simplygon again 
8) for each LOD that (7) makes apply a PBR material with vray complete map as diffuse color, also make a standard material with that map
9) export gltf with PBR mat, fbx with standard mat x2 
10) save the file and quit using quitMax #noPrompt

i don't think i can give you the script and have it work outside of our network sadly. 

we have a workaround which is having something that has max call a command to kill max at the end of our script, since the equivalent of calling "end task" makes this error not happen.

**Comment by noalak** [comment] 2018-07-10 13:19
Nice you found a workaround, could you share the exact command you are using to kill 3ds max on Windows ?

Still i would like to understand where the issue comes from.

Can you confirm that you experience an issue when simply openning and then closing 3ds max while babylon exporter dll are present (no DOS script, no Max script) ?

**Comment by johanos** [comment] 2018-07-19 13:46
Yeah the issue happens on normal operation i'll share a video. @mattWayfair  can share the killing command we made to work around this bug.

**Comment by johanos** [comment] 2018-07-19 13:48
here's the link to a ziped .mov file 
https://drive.google.com/file/d/1m5dxx2--xRhlwb93DHmlC46GwCeFBoRT/view?usp=sharing

**Comment by deltakosh** [comment] 2018-08-23 15:44
Closing for now as we cannot reproduce and it seems linked to custom scripts

**Closed by deltakosh** 2018-08-23 15:44 UTC
Labels: 3dsmax, bug

**Comment by ogmasoul3d** [comment] 2019-02-07 22:37
I get exactly the same problem when I run max in a amazon ami instace win10 and max2019.

I tried to add/remove all dependcies to this plugin in the /bin/assemblies/ folder

And all of them works except when i put max2babylon in there.

Then when I start max and close it directly without doing anything I get the same error on my virtual machine.

I do not get this problem on my local machine though using the same versions of the plugin and max.

So could be VM related. But max works fine in a vm before I put the plugin in..

**Comment by deltakosh** [comment] 2019-02-07 23:44
We plan to soon switch to Python so this error should be gone
