### ISSUE TITLE
Export cancelled: Invalid ID, can't deserialize. - 3dsmax 2018

### ISSUE THREAD

**Issue by VentuzDennisDworak** [BabylonJS/Exporters#812] opened 2020-05-06 11:07 UTC
Hey,

used some Mixamo meshes and animations to check glTF export.
Some went successfull, most of them contained scaling issues (Head is like a big bubble etc),..

anyway, after trying different export options, like bake animations, preprocess etc the export now failes ALWAYS with following error:

Export cancelled: Invalid ID, can't deserialize.

> 	System.Exception: Invalid ID, can't deserialize.
   at Max2Babylon.AnimationGroupList.LoadFromData(IINode dataNode)
   at Max2Babylon.AnimationGroupList.InitAnimationGroups(ILoggingProvider logger)
   at Max2Babylon.BabylonExporter.ExportAnimationGroups(BabylonScene babylonScene)
   at Max2Babylon.BabylonExporter.Export(ExportParameters exportParameters)
   at Max2Babylon.ExporterForm.<DoExport>d__21.MoveNext()

The same error got thrown now everytime i open the Babylon Animation Groups - rightclick

.net framework pops up with:

> ************** Exception Text **************
System.Exception: Invalid ID, can't deserialize.
   at Max2Babylon.AnimationGroupList.LoadFromData(IINode dataNode)
   at Max2Babylon.AnimationForm.AnimationForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Drigax** [comment] 2020-05-06 20:25
can you share your scene file, and the repro steps for causing this error?

**Comment by Drigax** [comment] 2020-05-06 22:44
Also @elpie89 does this sound familiar at all?

**Comment by elpie89** [comment] 2020-05-06 23:21
Seems like an animation group is still trying to access an ID of a node that no longer exists.
A simple trick is that you merge your scene in an empty file.
This will keep your data ...but the problem should be managed by the Exporter.
If you share the scene I can take a look

**Comment by Drigax** [comment] 2020-05-13 17:25
@VentuzDennisDworak do you have a scene that reproduces this that you can share?

**Comment by Drigax** [comment] 2020-05-15 15:33
I'm going to close this issue for now, since we're yet to get a repro. Feel free to reopen when you can provide one😊

**Closed by Drigax** 2020-05-15 15:33 UTC
Labels: 3dsmax, bug

**Comment by cptSwing** [comment] 2020-07-30 18:42
I have a file this happens with as well

```
[...]
Export animation groups
Export cancelled: Invalid ID, can't deserialize.
	System.Exception: Invalid ID, can't deserialize.
   at Max2Babylon.AnimationGroupList.LoadFromData(IINode dataNode)
   at Max2Babylon.AnimationGroupList.InitAnimationGroups(ILoggingProvider logger)
   at Max2Babylon.BabylonExporter.ExportAnimationGroups(BabylonScene babylonScene)
   at Max2Babylon.BabylonExporter.Export(ExportParameters exportParameters)
   at Max2Babylon.ExporterForm.<DoExport>d__21.MoveNext()
[...]
```

I had set up a number of animation groups with one specific set of nodes just fine, adding a different combination of nodes for an additional anim group kills it all unfortunately.. where can I send you my test file? :)

**Comment by Drigax** [comment] 2020-07-30 19:53
If you can share this publicly, feel free to zip and attach to a comment in
this thread in GitHub
