### ISSUE TITLE
Add support for 3dsMax 2020

### ISSUE THREAD

**Issue by jarnoburger** [BabylonJS/Exporters#534] opened 2019-06-05 10:26 UTC
I know i could get into nothing when trying the plugin for 2019 in 2020..
But its not working.. Hehehe :).
![image](https://user-images.githubusercontent.com/1609891/58949590-1856f000-878d-11e9-8088-857faca63d76.png)

**Comment by Drigax** [comment] 2019-06-05 18:21
Thanks, sounds like we need another project to target 3dsMax 2020. 

@kcoley do you have any insight as to what typically differs for the Max API assemblies for each version?
I'll most likely go off of your previous work for adding support for Maya2019 and looking at the differences between the other Max2Babylon projects.

I hope to get to this by the end of the month, as we should support the latest and greatest 3dsMax versions, but if anyone wants to take this on in the meantime, feel free.

**Comment by susares** [comment] 2019-06-06 14:35
Hi,
there have been some changes in the .Net SDK wrapper resulting in the above error message.

@Drigax there are no real insights when it comes to changes in new versions of the SDK. Sometimes Autodesk documents it the rest is fixing compilor errors. Basicly how i did the 2019 port.

I started to work on a 2020 port but did not push anything yet.
This is due to a critical error in the current 2020 .Net SDK wrapper resulting in 3dsmax crashing without error messages, stack traces or exceptions.
We have filed a bug with Autodesk that is currently under investigation and escalated to their engineering team. As soon as this bug is fixed a 3dsmax 2020 port should be in sight in a timely manner.
I also mentioned BabylonJS during the communiction with Autodesk on how it affects development.

The bug seems to be stuck rather deep in the .Net SDK internally affecting basicly IGame interface related classes/methods. Once you call them 3dsmax trips over and crashes a view cpu cycles later.
According to Autodesk IMaterial seems to be another candidate that shows this behavior. So any plugin written with the .Net SDK and using IGame or IMaterial interface are doomed currently.

**Comment by sebavan** [comment] 2019-06-10 20:05
@susares do you happen to have a public link to the issue ? or is it only kept internally on their side ?

**Comment by susares** [comment] 2019-06-11 06:25
@sebavan sorry I don't have a public link. just the internal API support and a internal change request number that it resulted in. I will comment back here once I get more information from Autodesk.

**Comment by Drigax** [comment] 2019-06-28 18:29
Hi @susares, is there any update from Autodesk with the bug report?

**Comment by susares** [comment] 2019-07-01 06:29
@Drigax magical coincidence. We just got confirmation from Autodesk, that the issue is being sorted out and scheduled for the next Update.

**Comment by sebavan** [comment] 2019-07-01 13:09
Amazing, can not wait to try it :-)

**Comment by Drigax** [comment] 2019-07-11 18:00
@susares, do you know when we can expect Autodesk to ship the next update with the fix?

**Comment by susares** [comment] 2019-07-12 06:59
@Drigax Nope sadly not. If it works like Max 2018/2019 should be around end of August to September.

**Comment by Drigax** [comment] 2019-07-23 16:01
closing this issue until 2020.2 is released.

**Closed by Drigax** 2019-07-23 16:01 UTC
Labels: 3dsmax, enhancement, help wanted

**Comment by magelanOpenSource** [comment] 2019-09-10 13:25
Hi,

3DS Max 2020.2 have been released a week ago.
Is it possible to release your exporter to support it ?

Thank you in advance. You make a great work

**Comment by Drigax** [comment] 2019-09-18 17:22
Hi @magelanOpenSource , I wanted to follow up to update that we finally have full support for Max 2020! :)
