### ISSUE TITLE
[Max] "Exportation cancelled: Object reference not set to an instance of an object." when exporting with DirectX shader

### ISSUE THREAD

**Issue by cptSwing** [BabylonJS/Exporters#405] opened 2018-12-09 21:49 UTC
Hey everybody. I am attempting to export a model that has a DirectX material applied in Max, set to "Interactive" (Stingray PBS) mode, and have a regular old Physical Material which in itself exports correctly set as it's Software Render Style. Not much happens on export:
![image](https://user-images.githubusercontent.com/18466732/49703358-54593000-fc04-11e8-8bfe-1d4371a6cfcc.png)

I'll gladly provide more information on request.

Also: More options regarding textures would be nice. Not compressing them to jpg first and foremost, using a custom folder structure, not giving the files resulting from an export bizzare names. But that's for a different thread I guess ;-)

Keep up the good work regardless. I've seen 2 or 3 updates to the plugin since I installed a week or two ago, your efforts are much appreciated!

**Comment by kcoley** [comment] 2018-12-13 20:42
@cptSwing sorry for the delay, I'll take a look when I get some cycles on this.

**Comment by kcoley** [comment] 2019-01-02 18:02
Hi @cptSwing do you have a sample scene that repros the issue?

**Comment by cptSwing** [comment] 2019-01-07 12:47
Hey @kcoley please excuse the late reply - I'll whip something up hopefully later today or tomorrow. Are you having trouble reproducing the error?

**Comment by kcoley** [comment] 2019-01-07 17:50
@cptSwing no problem!  Yes, I'm having trouble reproducing the error.  As another check, can you try against the latest version of the exporter to see if the error is still happening?

**Comment by cptSwing** [comment] 2019-01-09 18:50
Alrighty, here we are. I get the identical error using latest Babylon exporter, I'm afraid. It's not a showstopper, using a Shell material for viewport preview while being able to export works too now. 

[babylon_test.zip](https://github.com/BabylonJS/Exporters/files/2742153/babylon_test.zip)

**Comment by cptSwing** [comment] 2019-01-09 21:37
Ok it seems I spoke too soon - using a Multi/SubObj Material, which in turn is fed by Shell Materials with both a DirectX shader (for my Max viewport) and a Physical Material for exporting.. fail as well.

**Comment by kcoley** [comment] 2019-01-14 18:22
@cptSwing gotcha, I'll take a look

**Comment by kcoley** [comment] 2019-01-14 19:39
@cptSwing looks like this model is missing textures.  Would you be able to send them?

**Comment by kcoley** [comment] 2019-01-16 19:08
@cptSwing I just merged a fix for the error, which was caused by an undefined DirectX material property.

**Closed by kcoley** 2019-01-16 19:08 UTC
Labels: 3dsmax
