### ISSUE TITLE
Exportation cancelled. External component has thrown an exception

### ISSUE THREAD

**Issue by hassanalakbar** [BabylonJS/Exporters#108] opened 2018-03-03 15:31 UTC
Help please. When i try to export max scene to any format with using babylonjs exporter, it shows the error in exportation window.

Exportation cancelled. External component has thrown an exception

**Comment by deltakosh** [comment] 2018-03-03 15:32
Hello
Which version of 3ds max? Which OS?

**Comment by hassanalakbar** [comment] 2018-03-03 15:33
3Ds max 2015 windows 10 edu

**Comment by hassanalakbar** [comment] 2018-03-03 15:47
Tried to do it on another PC but get the same problem

**Comment by deltakosh** [comment] 2018-03-03 15:47
is it x64 or x86?

**Comment by hassanalakbar** [comment] 2018-03-03 19:57
Hi. Max 2015 windows 10 64 bit. But im try this on Max 2018 and all is
work. It would be better if it work on 2015 too.

3 марта 2018 г. 7:47 PM пользователь "David Catuhe" <
notifications@github.com> написал:

**Comment by deltakosh** [comment] 2018-03-03 19:59
Agree but I have no 2015 version.
Do you @noalak?

**Comment by hassanalakbar** [comment] 2018-03-03 20:37
No im hassanalakbar. I was find exporter for 2015 max version, bit its
didnt work. In the folder with versions of exporter you have exporter
version for max 2015

3 марта 2018 г. 11:59 PM пользователь "David Catuhe" <
notifications@github.com> написал:

Agree but I have no 2015 version.
Do you @noalak <https://github.com/noalak>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BabylonJS/Exporters/issues/108#issuecomment-370175430>,
or mute the thread

**Comment by noalak** [comment] 2018-03-09 14:15
@Jaskar does

**Comment by Jaskar** [comment] 2018-03-09 16:50
I'll test it on max2015 next week if needed (out office until wednesday), on Windows 10 home & pro first.

**Comment by Selmar** [comment] 2018-03-12 11:04
Same for me. Here's some more details. Seems to be related to the fix you wanted me to test, @noalak?

![image](https://user-images.githubusercontent.com/3010534/37280197-66d4edac-25ed-11e8-8f2a-7a6f7fea11f0.png)

**Comment by Jaskar** [comment] 2018-03-13 16:11
@Selmar noalak is out of office until 18/03/19. He'll check it then :)

**Comment by Ben-Mack** [comment] 2018-06-26 02:51
I'm having the same problem, but it only occurs on some specific scene (tried on both Max 2016 and 2018).

![babylonerrorcapture](https://user-images.githubusercontent.com/6309393/41886336-1ba14ab0-7926-11e8-8a0e-8dc1c9ac3b32.jpg)

**Comment by deltakosh** [comment] 2018-06-26 02:52
Can you share a scene with the issue?

**Comment by Ben-Mack** [comment] 2018-06-26 03:41
@deltakosh Ok, I'll prepare that scene.

In the meanwhile, I found a scene with another error, export process successfully but BabylonJS engine cannot display the GLB file with these errors:
![engineerror](https://user-images.githubusercontent.com/6309393/41887816-962569d2-792c-11e8-8605-a3fef6c87a08.PNG)

Download: (please remove .txt extension)
 - MaxFile: [Scene 1 - Error Primitives are missing.max.txt](https://github.com/BabylonJS/Exporters/files/2135473/Scene.1.-.Error.Primitives.are.missing.max.txt)
 - Exported GLB:  [01.glb.txt](https://github.com/BabylonJS/Exporters/files/2135472/01.glb.txt)

**Comment by Ben-Mack** [comment] 2018-06-26 04:36
Here is the scene with error `Exportation cancelled. External component has thrown an exception`
Download: https://we.tl/N5ZPF0MKo0

**Comment by Ben-Mack** [comment] 2018-06-26 07:45
Ok, I just found extractly which model cause exception error in that scene. 

Here is the Max file with only that model (instead of full scene like prev file):
[The-model-cause-exception-error.zip](https://github.com/BabylonJS/Exporters/files/2136045/The-model-cause-exception-error.zip)

**Comment by noalak** [comment] 2018-06-26 13:32
@Bloadrick is working on it

**Comment by Selmar** [comment] 2018-07-03 13:03
Is there any progress on this? Or is there a workaround? 

It's starting to become a serious issue for some models we have, same error as @Ben-Mack

**Comment by noalak** [comment] 2018-07-03 13:36
The first issue Ben-Mack reported is caused by the InitializeData method because a mesh does not have geometry (mesh QQ86130827接图2099).
We have fixed it but other bugs are present. We are investigating on them before doing a PR.
Expect a PR before end of week.

@Selmar Which error message do you have exactly ?

**Comment by Selmar** [comment] 2018-07-03 14:43
It looks exactly the same, with the get_InitializeData() call etcetera.

Apparently it was because of an edit poly that wasn’t collapsed (I don’t know the details). If we get it again after you pushed your fixes, we’ll submit an issue.

De : Tambrun Fabrice <notifications@github.com>
Envoyé : Tuesday, July 3, 2018 15:37
À : BabylonJS/Exporters <Exporters@noreply.github.com>
Cc : Selmar <selmar21@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [BabylonJS/Exporters] Exportation cancelled. External component has thrown an exception (#108)


The first issue Ben-Mack reported is caused by the InitializeData method because a mesh does not have geometry (mesh QQ86130827接图2099).
We have fixed it but other bugs are present. We are investigating on them before doing a PR.
Expect a PR before end of week.

@Selmar<https://github.com/Selmar> Which error message do you have exactly ?

**Comment by deltakosh** [comment] 2018-07-03 17:05
A fix was merged. Can you confirm the fix?

**Comment by noalak** [comment] 2018-07-03 17:07
@Selmar @Ben-Mack is it good for both of you ?

@Ben-Mack VRay materials and lights are not supported by the exporter. Advanced texturing features such as ColorCorrection or Mix are not supported as well.

**Comment by Ben-Mack** [comment] 2018-07-04 02:00
Thank you @noalak ! 
I can confirm it working now, both of my previous errors are gone.

Just found another minor bug when a map has uppercase extension like `JPG`, leads to `Exportation cancelled`:
![jpg](https://user-images.githubusercontent.com/6309393/42252707-0c006710-7f68-11e8-818b-eb8dd543e9bb.PNG)

**Closed** 2018-07-12 15:37 UTC
Labels: 3dsmax, bug
