### ISSUE TITLE
[3dsMax] Light children with shadows on cause scene loading failure

### ISSUE THREAD

**Issue by noalak** [BabylonJS/Exporters#755] opened 2020-02-11 09:14 UTC
When a light has children and the light has shadows on, the babylon scene fails to load in the sandbox.

Error message:
![2020-02-11_10h13_38](https://user-images.githubusercontent.com/20560340/74223522-2e6f6580-4cb7-11ea-8a8f-7a5af1d2bcc8.png)

**Comment by Drigax** [comment] 2020-03-05 01:28
I can't consistently reproduce this. It appears to be caused by the serialized shadowGenerators being pointed to the light node dummy parent node, but I don't know why this happened. Suddenly my test scene exported without issue. closing as no-repro, but I'll reopen to investigate if I get a 100% repro case.

**Closed by Drigax** 2020-03-05 01:28 UTC
