### ISSUE TITLE
Adding MAX 2024 to the Installer

### ISSUE THREAD

**Issue by BeachCat1** [BabylonJS/Exporters#1112] opened 2024-01-31 17:11 UTC
I would like to auto install the Babylon JS Exporter to MAX 2024 but that option is missing in the Installer exe:

![2024-01-31 11_11_07-Settings](https://github.com/BabylonJS/Exporters/assets/158317267/f7f75f06-ddab-4820-a01b-74050ca62430)

**Comment by thomlucc** [comment] 2024-01-31 18:43
Duplicate of https://github.com/BabylonJS/Exporters/issues/1087

**Closed by thomlucc** 2024-01-31 18:43 UTC

**Comment by FrogsInSpace** [comment] 2024-08-31 06:51
I created a pull request which adds 3ds Max 2024/2025 support to the installer
babylonjs exporter for 3ds Max 2025 is in the works, but due to the removal of central menu APIs from the 3ds Max 2025 SDK this will still take some time...
