### ISSUE TITLE
Export issue with an animated rig

### ISSUE THREAD

**Issue by vaaleerian** [BabylonJS/Exporters#900] opened 2020-12-02 09:09 UTC
Hello, I have an issue with the exporter. I have an animated rig with a morpher and when I want to export my animation, I have this message :

Export canceled: The object reference is not defined as an instance of an object.
	System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Maya2Babylon.BabylonExporter.ExportAnimationGroups(BabylonScene babylonScene)
   à Maya2Babylon.BabylonExporter.Export(ExportParameters exportParameters)
   à Maya2Babylon.Forms.ExporterForm.<DoExport>d__32.MoveNext()

Do you have an idea of what is going wrong?
![2020-12-02 10_07_37-Babylon js - Export scene to babylon or glTF format v20201123 8](https://user-images.githubusercontent.com/75361967/100852177-6a61fa00-3486-11eb-9ab9-618e4a35b76e.png)

Thank you in advance for your help.

**Comment by pandaGaume** [comment] 2020-12-02 17:56
could you send me the scene for testing ?

**Comment by stanlo** [comment] 2020-12-02 22:04
The issue is that both skinning and morphs are not presently supported by the BabylonJS exporter. My team would like this feature, so that we can have an easy process to generated models with both skins and morph targets. Is it possible to know when this feature might be implemented?

**Comment by tjjung-google** [comment] 2020-12-02 22:08
Yes I'm facing same issue as well. 
fyi, w/fb tool I was able to export together.

**Comment by pandaGaume** [comment] 2020-12-02 23:08
Issue text is related to a null pointer which mean... null pointer. You may help us to identify the issue by sharing a repro scene. :-)

**Comment by stanlo** [comment] 2020-12-02 23:50
Should I open a separate issue regarding the feature?

**Comment by vaaleerian** [comment] 2020-12-03 09:10
Thank you very much for your help! Here is my scene:

[Scene_Avec_Fourmi_04.zip](https://github.com/BabylonJS/Exporters/files/5634883/Scene_Avec_Fourmi_04.zip)

What's strange is that I've already managed to export models with both skin and morph targets. That's why I didn't understand and asked for your help.

**Comment by pandaGaume** [comment] 2020-12-03 09:31
@stanlo as vaaleerian sayed, she already export both, so no need to open an issue, except if you're experiencing a dysfonction. Regards.

**Comment by vaaleerian** [comment] 2020-12-03 09:35
I've already managed to export both yes, but with the scene I sent, the export doesn't work and I don't know why.

**Comment by pandaGaume** [comment] 2020-12-03 10:57
@vaaleerian  voici la scène après quelques fix sur le code (without textures)
[fourmi.zip](https://github.com/BabylonJS/Exporters/files/5635550/fourmi.zip)
Tell me if this is working as expected. There is still some minor issues validating the gltf but i guess it let you moving forward. If ok i will make a pr and the new version will be available soon.

**Comment by pandaGaume** [comment] 2020-12-03 11:00
@stanlo if you've a reproductible scene with recommandation you're very welcome.

**Comment by vaaleerian** [comment] 2020-12-03 11:54
Thanks for your help. But as you can see in the video linked, the gltf didn't export the morph targets.
[BabylonVsMaya.zip](https://github.com/BabylonJS/Exporters/files/5635851/BabylonVsMaya.zip)

**Comment by pandaGaume** [comment] 2020-12-03 12:29
Thanks for the clarification. I will close this issue which is about the exception, and open a new one with the video and the file as support.

**Comment by pandaGaume** [comment] 2020-12-03 14:31
@vaaleerian btw, did you try to export morph without deleting the target ?? the issue we have here is that the Maya SDK does NOT find the target and i suspect this is because it has been baked into the BlendShape Deformer. could you confirm ?

**Comment by vaaleerian** [comment] 2020-12-03 14:53
I'm sorry but I'm not familiar with coding, I'm just a 3D artist and I didn't create the asset. How can I export without deleting the target and where can I find the target if it has been bake to the BlendShape Deformer.

**Closed** 2020-12-03 18:09 UTC
Labels: maya

**Comment by pandaGaume** [comment] 2020-12-07 11:30
@vaaleerian is this more correct ?
[fourmi.zip](https://github.com/BabylonJS/Exporters/files/5652320/fourmi.zip)

.. honestly maya is a nightmare about SDK and coding.. 
In all case once the fix will be publish, you must take care of 

- reducing the number of unused morph target
- carefully choose the right animation frame as reference
- and set all the morph weight to zero before import

we will modify the documentation accordingly

Merci.
