### ISSUE TITLE
Maya Exporter - Camera scale is null

### ISSUE THREAD

**Issue by crmabs** [BabylonJS/Exporters#643] opened 2019-10-05 03:11 UTC
After updating the exporter plugin to the latest version the camera's scale gets written as null. 
All the validators, readers, viewers go crazy. 

This is how it looks like in gltf:
{
            "camera": 0,
            "translation": [
                4.490398,
                9.568486,
                -6.398381
            ],
            "rotation": [
                -0.09149666,
                0.899486542,
                0.36159128,
                0.22760509
            ],
            "scale": null,
            "name": "cameraProd"
        }

There are other issues with this last version but this one is critical. The others are - as far as I saw it - just warnings.

**Comment by Drigax** [comment] 2019-10-06 11:10
Thanks for the report, I'll take a look at it ASAP. To help me root cause quickly, which exporter are you using, and can you provide a test scene?

**Comment by crmabs** [comment] 2019-10-06 17:47
"asset": {
        "version": "2.0",
        "generator": "babylon.js glTF exporter for Maya 2018 v1.4.0"
    }, 

i hope this helps. it was the latest at the time of the issue was created

**Comment by Drigax** [comment] 2019-10-07 18:36
Great, I was able to reproduce this using this scene here:
[Exporters_643.zip](https://github.com/BabylonJS/Exporters/files/3698939/Exporters_643.zip)

**Comment by Drigax** [comment] 2019-10-07 19:16
Fix is pretty trivial, turns out we weren't setting the camer scale in the babylon export/scene data extraction phase since camera.scale isn't used in .babylon. Added the assignment appears to fix the export. Fix should be checked in and available within the hour.

Please feel free to open issues for any problems you run into 😊

**Closed by Drigax** 2019-10-07 19:16 UTC
Labels: bug, maya
