### ISSUE TITLE
the outerConeAngle of lights needs to be divided by 2

### ISSUE THREAD

**Issue by aguaviva** [BabylonJS/Exporters#689] opened 2019-11-22 10:06 UTC
I think you are exporting there the FOV angle instead the value the specs require:

![image](https://user-images.githubusercontent.com/5200915/69416659-62ba3200-0d17-11ea-9192-f7939b9365bc.png)

Notice the angle goes from the center to the edge, and that is half the angle.

Oh! And the same thing goes for the innerConeAngle.

**Comment by Drigax** [comment] 2019-11-23 00:26
Ah, looks like a simple fix, but I want to setup a test scene just to confirm that the spotlight angle according to the Maya API is measured centered on the direction ray, while the glTF spec expects it to be measured from the center of the direction ray:

![image](https://user-images.githubusercontent.com/3952729/69469287-dfafd080-0d44-11ea-98ea-ad7c96726a6e.png)

**Comment by Drigax** [comment] 2019-11-23 01:52
Ok, I think I have a functional test for this:

I have a simple scene where there are a nimber of spotlights positioned 1m above a plane, pointed downwards.

The spotlights have a varying "angles" in Maya: 5.625, 11.25, 22.5, 45.

If maya shares the same convention as glTF, I'd expect the resulting penumbras to have radii of:
radius = 1m * tanθ
[~.1m, ~.2m, ~.4m, ~1m] = 1m * tan([5.625, 11.25, 22.5, 45])

constructed in Maya, we get:
![image](https://user-images.githubusercontent.com/3952729/69471105-a0877c80-0d50-11ea-80ec-1e15653a2140.png)

Where our widest light has a penumbra of ~.5m (given that the spotlight projection plane has a width of 1m.

Ok, you're completely right here.

**Comment by Drigax** [comment] 2019-11-23 02:43
Importing the .babylon exported scene, it looks like they share the same convention. Babylon must be performing some falloff of the spotlight, so I had to increase the intensity to a ridiculous 100000:
![image](https://user-images.githubusercontent.com/3952729/69471761-e72ca500-0d57-11ea-8bba-f6514161bcd6.png)

**Comment by Drigax** [comment] 2019-11-23 02:46
Testing the gltf export we get:
![image](https://user-images.githubusercontent.com/3952729/69471794-50141d00-0d58-11ea-98c4-15cc00b2f0a6.png)

Crap. There must be some issue with how we are resolving the light orientation. I'll have to get back to this Monday to fix that as well.

**Comment by Drigax** [comment] 2019-11-23 02:50
In the meantime, manually applying a +270deg X rotation yields:
![image](https://user-images.githubusercontent.com/3952729/69471840-d16baf80-0d58-11ea-9aed-a70b9946c78f.png)

Which supports our original hypothesis. Looks like we should only modify the angle during our Babylon -> glTF export phase. I can check in a fix quickly.

**Comment by Drigax** [comment] 2019-11-26 00:39
Looking at 3dsMax, this appears to share the same "cone angle" nomenclature:

![image](https://user-images.githubusercontent.com/3952729/69586378-462c2d00-0f97-11ea-9ec1-da1cd590800f.png)

Exported to .Babylon, we get:
![image](https://user-images.githubusercontent.com/3952729/69586726-5abcf500-0f98-11ea-8b75-ee8f6285eb82.png)

And to glTF from Max we get:
![image](https://user-images.githubusercontent.com/3952729/69589641-a9bb5800-0fa1-11ea-8cb6-44d77d58e7b3.png)

crap again. I'll open #696 to address the orientation issue as well.
Adjusted, looks like the issue is how we convert our in-memory babylon scene to glTF, this should be made to the shared exporter:
![image](https://user-images.githubusercontent.com/3952729/69589818-22221900-0fa2-11ea-941d-fd3120b08f71.png)

**Comment by Drigax** [comment] 2019-11-26 00:51
Fix looks good, after all that talking and testing, it was a single line:
![image](https://user-images.githubusercontent.com/3952729/69590288-d2dce800-0fa3-11ea-9045-f542321df1e5.png)

**Comment by Drigax** [comment] 2019-11-26 01:10
Currently we don't support lightInnerAngle, but I'm interested in improving that support as well. 

Currently I'm struggling to find some examples in the schema, and in Maya/3dsMax but if you can help with some samples that show the expected behavior, I'd be happy to make those changes as well.

**Closed** 2019-11-26 01:13 UTC
Labels: bug, maya
