### ISSUE TITLE
MaxtoBabylon latest update- export error.

### ISSUE THREAD

**Issue by Mustard-Design** [BabylonJS/Exporters#571] opened 2019-07-23 08:07 UTC
When exporting (Export & Run) from 3dsMax 2019 a 404 error (texture not found) occurs when the browser opens (Chrome and Firefox). Both glb and gltf file types fail.
Previous version (10 days ago) work fine on the same scene (Animation groups deleted and created from scratch).

Update. On further examination, neither gltf or glb files export our character correctly. Biped Animation is not converted and no morph targets work.

**Comment by Drigax** [comment] 2019-07-23 16:04
Interesting, I haven't noticed this in my own testing, but I'll take a look.

Do the files still load when manually added to the babylon sandbox?

**Comment by Mustard-Design** [comment] 2019-07-23 16:07
Hi Thanks for looking into this. No the files are still broken when dragging into the sandbox.
If I have simple texture (no bitmaps etc) applied to the model, then it exports and runs the sandbox, but all biped animation is corrupted.
If I add the correct textures to the model (simple png and jpgs) then it will not export at all and I get a 404 error.

**Comment by Drigax** [comment] 2019-07-23 17:03
Can you share your scene files? I'm unable to reproduce the 404 with a simple scene.

**Comment by Mustard-Design** [comment] 2019-07-23 17:07
I can, they are under NDA and copyright so I'd have to share them securely with you.

**Comment by Drigax** [comment] 2019-07-23 17:12
Would email suffice?: whoisdrigax@gmail.com

**Comment by Mustard-Design** [comment] 2019-07-23 17:28
Hi Yes thankyou. 
I will email you the file. Please don't share this as it's sensitive data, under strict NDA.
Appreciate any help you can offer.

**Comment by Drigax** [comment] 2019-07-24 23:48
Thank you for sharing, this definitely wrong, both our .Babylon export and glTF export seems to fail with our skinned meshes where either the animation of the skeleton or skinning of the child meshes are incorrect.

However, I am unable to consistently reproduce the 404 issue, the only time when that this occurred for me is when I performed an export and run using a file path that doesn't exist on my system:
![image](https://user-images.githubusercontent.com/3952729/61835964-e54ae780-ae32-11e9-8ee6-1d6519230675.png)

**Comment by Mustard-Design** [comment] 2019-07-26 09:52
No problem, it seems  skinned mesh +morphs are not working at all right now.
Also I’ve just created a simple export for a sphere and I’m still getting 404 errors.
I’ve attached a screengrab and the 3dsmax file.(2019)


I think the issue is that the exporter is assigning a material name that does not correspond to the actual bitmap reference maybe?
![image](https://user-images.githubusercontent.com/53213073/61943413-3c67ce00-af93-11e9-9f42-3274ae695dc0.png)

[babyl-test.zip](https://github.com/BabylonJS/Exporters/files/3435221/babyl-test.zip)

**Comment by Drigax** [comment] 2019-07-26 18:01
Your screenshot is a bit hard to read, but are you exporting the textures to the same folder as the gltf?

**Comment by Drigax** [comment] 2019-07-26 18:16
I'm not sure what to tell you regarding your 404, the scene that you uploaded works fine for me as well. I know that firefox is not supported regarding export&run. can you please upload a higher res screen capture of your exporter dialog & log, the error message you see, and your browser's developer console log (F12)?

**Comment by Drigax** [comment] 2019-08-01 00:21
I was able to figure out what was causing our skeletal animations to break when exporting glTF, it looks like we've always missed some of the bone animations due to their naming schema, so they're not included in the BabylonScene we create on export. 

Since we changed our AnimationGroup representation, we had to change the logic to derive the animated nodes from the targets of the animations included in the group, which exposed this bug.

**Comment by Mustard-Design** [comment] 2019-08-01 08:02
That's great news. Glad you managed to find the bug. As for the textures crashing the sandbox I think it's just the Texture Folder path that is causing the issues. If I point it as a specific folder then it either crashes when compiling or crashes when opening the Sandbox, however if I leave the texture folder path blank then it exports and runs without error.

**Comment by Drigax** [comment] 2019-08-01 15:52
Ok, does the folder path that you point textures to exist?

**Comment by Drigax** [comment] 2019-08-02 15:19
I'm going to close this issue since the mesk skinning regression was fixed, but please feel free to open a new issue if you can consistently reproduce your export 404 with detailed repro instructions

**Closed by Drigax** 2019-08-02 15:19 UTC

**Comment by Drigax** [comment] 2019-08-02 20:22
I believe I also found a contributor to your export 404, since the refactor introduced a bugfix used in the Maya exporter that renamed our textures on glTF export. Hopefully this also helps resolve your issue.
