### ISSUE TITLE
[Max][glTF] BaseColor texture turns white when specularLevel too high

### ISSUE THREAD

**Issue by Ben-Mack** [BabylonJS/Exporters#466] opened 2019-03-18 02:03 UTC
In 3ds Max, if material type Standard has high `Specular Level` value (like above 200), the output diffuse texture will become blank white.

This behaviour only occurs on glTF format, texture exported using Babylon format still working fine.

Looking through the source, I think it might related to this function:
https://github.com/BabylonJS/Exporters/blob/5679018c6386043af7ec8c0d4374faeded8c4451/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Material.cs#L589

**Comment by deltakosh** [comment] 2019-03-18 14:40
Yes the problem is that there is no straightforward transfer between non PBR (standard) and PBR material 

I highly recommend to use PBR directly in 3dsmax if you plan to export to gltf.

Adding @bghgary for additional thoughts

**Comment by Ben-Mack** [comment] 2019-03-21 02:50
I think this issue should be considered as a bug. Because even when there's no correct Standard to PBR conversion, the exporter should not turns the diffuse texture into blank white...

**Comment by deltakosh** [comment] 2019-03-21 15:37
WOuld like to get @bghgary thoughts before marking it as a bug

**Comment by bghgary** [comment] 2019-03-21 22:59
This one is hard for me to judge since I don't know Max's materials. Does exporting to the babylon format and then serializing to glTF have the same issue? If so, can you send me the export babylon file?

**Comment by Ben-Mack** [comment] 2019-03-22 09:35
I've prepared 2 cases: One with specular level at 200 (named `hi-specular`), one with specular level at 50 (named `lo-specular`)

For each case, I've exported both babylon and gltf format into separate folders.

The material in Max is simply a default Standard material with a bitmap in diffuse slot and the accordingly specular level for each case.

Download: [Blank-tx-on-hi-specular.zip](https://github.com/BabylonJS/Exporters/files/2995795/Blank-tx-on-hi-specular.zip)

**Comment by bghgary** [comment] 2019-03-22 16:33
I think the Max exporter is still using the PBR spec-gloss conversion to convert a standard material to metal/rough, which is not right. @deltakosh @Drigax

**Comment by Drigax** [comment] 2019-04-23 18:07
I don't think this is a perfect solution, but reusing our Babylon->GLTF conversion for the Babylon->GLTF converter portion of the 3dsMax exporter should at the very least prevent us from exporting shiny materials as metallic, and improperly changing the material base color based off of its perceived shininess.

**Closed by Drigax** 2019-04-23 18:07 UTC
Labels: 3dsmax, bug
