### ISSUE TITLE
3ds Max 2021: GLB export merges O/R/M jpg files into a ORM png file

### ISSUE THREAD

**Issue by cptSwing** [BabylonJS/Exporters#844] opened 2020-06-15 14:16 UTC
I exported a glb file and unpacked it to gltf (via Visual Studio Code gltf tools); even though all source files are jpg files, the mixmaps are exported as png:

![image](https://user-images.githubusercontent.com/18466732/84668118-79c6a880-af23-11ea-81e2-a602af8e545e.png)

This does NOT happen when exporting to gltf; here the mixmaps are generated as jpg

**Comment by Drigax** [comment] 2020-06-16 17:40
Ah, I see originally we default to exporting any merged Basecolor+alpha map to png, I assume that we're doing the same for O/R/M. since we really don't need alpha for this, I'll see if we can prevent this behavior, thanks.

**Comment by pandaGaume** [comment] 2020-09-18 11:03
Hi @cptSwing , I will investigate the subject. Do you mind to share the project file which highlight this issue, (or any similar 3DSmax file to reproduce the issue), And Exporter Script configuration options. Thank's for your valuable colaboration.

**Comment by wandrzej** [comment] 2020-10-28 21:30
I have an opposite issue. I have my maps for Occlusion Roughness and Metallic in png and the ORM file format is jpg, but other maps (normal or color) end up being saved as png. 
Max 2020 on the latest plugin version

**Comment by pandaGaume** [comment] 2020-10-29 09:26
@wandrzej this is the actual normal behavior defined into the code. We gonna change this by proposing a clear statement about how the format will be or not beeing affected by merge operation, but we will certainly push png as preferred solution because it's lossely in term of data. The base of the discussions/choices was about the Alpha channel. BTW, did you try to export as GLB?? Does the file is still jpg when extracting the data (using vs code plugin) ??

**Comment by wandrzej** [comment] 2020-10-29 11:00
I haven't tried to unpack a glb in VS, but I've noticed something else that is quite interesting. After uninstalling the plugin and reinstalling it, the exporter started to generate png files again. I'm not 100% sure, but this might have happened after I've switched on the KHR_texture_transform option and despite turning it off, the jpg format persisted.

**Comment by pandaGaume** [comment] 2020-10-29 18:02
I mean ".**jpg**" extension is hard coded into [this line](https://github.com/BabylonJS/Exporters/blob/6519debf6da9b2c1df07ca4ef3aa24ba56b62e50/3ds%20Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs#L561), which lead to generate a jpg when exporting ORM to gltf, no matter the options. I'm interest by the behavior you have with the KHR options.. if you have a scene and a way to reproduce.

**Closed** 2020-11-18 21:01 UTC
Labels: 3dsmax, bug, need repro, working on
