### ISSUE TITLE
BabylonJS_Exporters error

### ISSUE THREAD

**Issue by AndresCH10** [BabylonJS/Exporters#661] opened 2019-10-25 11:51 UTC
I have a problem, when I install the BabylonJS_Exporters, it does not give me any errors and the program does not open

Any solution ? The answer is urgent.

Thank you.

Version -->CD Release 20191023.6

**Comment by Drigax** [comment] 2019-10-25 14:43
A few questions to help me debug this:

What tool and version are you installing the exporters with?
How are you installing the exporters?
Does the program launch then crash?
Do you have any Windows event logs?

**Comment by Drigax** [comment] 2019-10-25 15:05
![image](https://user-images.githubusercontent.com/3952729/67582210-2b4b6c00-f6fe-11e9-87c2-7d225d11b623.png)
I have a Max 2019 installation on my current machine that appears to work fine.

**Comment by Drigax** [comment] 2019-10-25 15:29
Likewise Maya 2019 looks like it works as well:
![image](https://user-images.githubusercontent.com/3952729/67583986-8fbbfa80-f701-11e9-9f31-a680dfff8c42.png)

**Comment by Drigax** [comment] 2019-10-25 15:30
I'm closing this issue as I am unable to reproduce this, but please feel free to re-open this if you have any more information that might help me reproduce what you are seeing :'(

**Comment by AndresCH10** [comment] 2019-10-25 15:31
Good afternoon.

On my PC, I had to do a total windows restart, the global installer for the max and maya programs, that is, the babylonJS_Exporter.exe.

The error comes when I extract the application from the ZIP, it doesn't open the program and I don't get any error.

**Comment by Drigax** [comment] 2019-10-25 15:33
When you launch the application, do you get this smart screen warning?
![image](https://user-images.githubusercontent.com/3952729/67584262-12dd5080-f702-11e9-8391-e6e3825e5f71.png)

**Comment by AndresCH10** [comment] 2019-10-25 15:35
yes, I get the message to open as an administrator, but when I open it I get the cursor circle loading but nothing else appears

**Comment by Drigax** [comment] 2019-10-25 15:40
I'm not sure how well I can help debug this, this may be an issue with your particular system.

Can you check your Events logs for anything involving Babylon_Exporters.exe?
What version of Windows are you using?
Do you have another computer that you can test with?

**Comment by AndresCH10** [comment] 2019-10-25 15:42
I have windows 10-64 Bits.

I have another computer, but the problem is that its operating system is iOS.

**Comment by Drigax** [comment] 2019-10-25 15:48
I'd try installing any available updates for your system, and ensuring that you have .NET Framework 4.7.3 Runtime installed on your system as well. Though since you're running Windows 10, the .NET framework version shouldn't be an issue.

Can you try running winver to get the Windows 10 build number?

**Comment by AndresCH10** [comment] 2019-10-25 15:52
I am just installing all the updates that the computer asks for and it has restarted me.
The process may take a while.
As soon as I have windows operational.

I will do the test you told me

**Comment by AndresCH10** [comment] 2019-10-25 16:44
After installing the updates, he opened the application.

Now I can see the record that I attached in the image


------>IMG
![Captura de pantalla (1)](https://user-images.githubusercontent.com/56534602/67588871-73e34380-f757-11e9-8f15-ecc7c8544955.png)

**Comment by Drigax** [comment] 2019-10-25 16:51
Ah, yes i noticed that as well. I broke that when i changed the release channel a few days ago #662 was just checked in to address this, followed by #663 to increment the version number. Can you try using the next installer included in the next release? It should have just been published:
https://github.com/BabylonJS/Exporters/releases/tag/Release20191025.4

**Comment by AndresCH10** [comment] 2019-10-25 16:54
very well, I will try this version, when I have it installed, I will inform if it has been fixed

**Comment by Drigax** [comment] 2019-10-25 20:23
@AndresCH10 did you have any luck with the installation?

**Comment by AndresCH10** [comment] 2019-10-26 13:48
@Drigax Yes, solved, it has been installed perfectly.
thank you

**Comment by Drigax** [comment] 2019-10-26 16:07
Glad I could help 😁

**Closed by Drigax** 2019-10-26 16:07 UTC
Labels: Installer
